# Generated by Django 3.2 on 2021-05-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmimeasurement',
            name='bmi',
            field=models.FloatField(null=True),
        ),
    ]
