# Generated by Django 3.2 on 2021-05-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_bmimeasurement_bmi'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmimeasurement',
            name='message',
            field=models.CharField(choices=[('underweight', 'UNDERWEIGHT'), ('normal', 'NORMAL'), ('overweight', 'OVERWEIGHT'), ('obese', 'OBESE')], max_length=255, null=True),
        ),
    ]
