# Generated by Django 3.2 on 2021-05-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210511_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmimeasurement',
            name='message',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
