# Generated by Django 3.2 on 2021-05-21 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_bmimeasurement_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmimeasurement',
            name='name',
        ),
    ]
