# Generated by Django 3.2 on 2021-05-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_bmimeasurement_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmimeasurement',
            name='name',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
